import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { Topic, PrototypeData, UserProfile } from "../types";

export const generateDesignThinkingReport = async (
  topic: Topic,
  refinedProblem: string,
  prototype: PrototypeData | null,
  scores: { creativity: number; understanding: number; innovation: number; overallScore: number },
  userProfile: UserProfile
) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Retrieve states from localStorage
  const empathizeSaved = localStorage.getItem(`zupskill_selected_perspective_${topic.id}`);
  let empathyData = null;
  if (empathizeSaved) {
    try {
      empathyData = JSON.parse(empathizeSaved);
    } catch (e) {}
  }

  const defineSaved = localStorage.getItem(`zupskill_define_${topic.id}`);
  let defineData = null;
  if (defineSaved) {
    try {
      defineData = JSON.parse(defineSaved);
    } catch (e) {}
  }

  const ideasSaved = localStorage.getItem("zupskill_sim_ideas");
  let topIdeas: string[] = [];
  if (ideasSaved) {
    try {
      const ideasArr = JSON.parse(ideasSaved);
      topIdeas = ideasArr.slice(0, 5).map((i: any) => i.text);
    } catch (e) {}
  }

  const completionDate = new Date().toLocaleDateString();

  // Helper for footer
  const addFooter = (doc: jsPDF, pageNumber: number, totalPages: number) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Generated by Zupskill | DT Innovation Lab`, margin, pageHeight - 12);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, pageHeight - 12, { align: "right" });
  };

  // Helper for text wrapping
  const writeWrappedText = (text: string, x: number, y: number, maxWidth: number, font: string, style: string, size: number, color: number[]) => {
    doc.setFont(font, style);
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return lines.length * (size * 0.4); // approximate height taken
  };

  let currentY = margin;

  // Load ZupSkill Logo
  try {
    const logoImg = new Image();
    logoImg.crossOrigin = "Anonymous";
    logoImg.src = "https://res.cloudinary.com/dmyxvewda/image/upload/v1731665476/ZupSkill_Blue_rxyo7c.png";
    await new Promise((resolve, reject) => {
      logoImg.onload = resolve;
      logoImg.onerror = reject;
    });
    const logoWidth = 35;
    const logoHeight = (logoImg.height / logoImg.width) * logoWidth;
    doc.addImage(logoImg, "PNG", pageWidth - margin - logoWidth, margin, logoWidth, logoHeight);
  } catch (err) {
    // Fallback to fake logo box if image fails to load
    doc.setFillColor(6, 182, 212);
    doc.roundedRect(pageWidth - margin - 20, margin - 5, 20, 20, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text("ZS", pageWidth - margin - 14, margin + 7);
  }

  // PAGE 1 HEADER
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(30, 41, 59);
  doc.text("Design Thinking Report", margin, currentY);
  
  currentY += 10;
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by Zupskill", margin, currentY);

  currentY += 6;
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated On: ${completionDate}`, margin, currentY);

  currentY += 15;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 10;

  // PROJECT INFORMATION
  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    theme: "plain",
    styles: { cellPadding: 2, fontSize: 11 },
    columnStyles: { 0: { fontStyle: "bold", textColor: [71, 85, 105], cellWidth: 60 }, 1: { textColor: [15, 23, 42] } },
    body: [
      ["Project / Challenge Name", topic.title],
      ["Challenge Category", topic.trendingTag || "General"],
      ["Completion Date", completionDate],
      ["Overall Simulation Score", `${scores.overallScore}%`],
    ],
  });

  currentY = (doc as any).lastAutoTable.finalY + 15;

  // Helper for Section Titles
  const addSectionTitle = (title: string, yPos: number) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text(title.toUpperCase(), margin, yPos);
    doc.setDrawColor(6, 182, 212);
    doc.line(margin, yPos + 2, margin + 30, yPos + 2);
    return yPos + 10;
  };

  currentY = addSectionTitle("DESIGN THINKING JOURNEY", currentY);

  // STEP 1
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Step 1: Choose a Topic", margin, currentY);
  currentY += 6;
  
  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: { fillColor: [248, 250, 252], textColor: [71, 85, 105], fontStyle: "bold" },
    bodyStyles: { textColor: [15, 23, 42] },
    body: [
      ["Selected Challenge", topic.title],
      ["Context", topic.description]
    ],
  });
  currentY = (doc as any).lastAutoTable.finalY + 12;

  // STEP 2
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Step 2: Empathize", margin, currentY);
  currentY += 6;

  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: { fillColor: [248, 250, 252], textColor: [71, 85, 105], fontStyle: "bold" },
    bodyStyles: { textColor: [15, 23, 42] },
    body: [
      ["Key User", empathyData?.name || "Not provided"],
      ["User Pain Points", empathyData?.frustrations ? empathyData.frustrations.join(", ") : "Not provided"],
      ["Empathy Insights", empathyData?.story || "Not provided"]
    ],
  });
  currentY = (doc as any).lastAutoTable.finalY + 12;

  // STEP 3
  // Check page break
  if (currentY > pageHeight - 60) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Step 3: Define", margin, currentY);
  currentY += 6;

  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: { fillColor: [248, 250, 252], textColor: [71, 85, 105], fontStyle: "bold" },
    bodyStyles: { textColor: [15, 23, 42] },
    body: [
      ["Problem Statement", defineData?.finalProblem || refinedProblem || "Not provided"],
      ["How Might We", defineData?.howMightWe || "Not provided"],
    ],
  });
  currentY = (doc as any).lastAutoTable.finalY + 12;

  // STEP 4
  if (currentY > pageHeight - 60) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Step 4: Ideate", margin, currentY);
  currentY += 6;

  const ideateBody = topIdeas.length > 0 
    ? topIdeas.map(idea => ["Idea", idea])
    : [["Ideas", "Not provided"]];

  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: { fillColor: [248, 250, 252], textColor: [71, 85, 105], fontStyle: "bold" },
    bodyStyles: { textColor: [15, 23, 42] },
    body: ideateBody,
  });
  currentY = (doc as any).lastAutoTable.finalY + 12;

  // STEP 5
  if (currentY > pageHeight - 80) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Step 5: Prototype", margin, currentY);
  currentY += 6;

  autoTable(doc, {
    startY: currentY,
    margin: { left: margin, right: margin },
    theme: "grid",
    headStyles: { fillColor: [248, 250, 252], textColor: [71, 85, 105], fontStyle: "bold" },
    bodyStyles: { textColor: [15, 23, 42] },
    body: [
      ["Title", prototype?.title || "Not provided"],
      ["Description", prototype?.description || "Not provided"],
      ["How it solves the problem", "Included in prototype description"],
      ["Expected user benefit", "Included in prototype description"],
    ],
  });
  currentY = (doc as any).lastAutoTable.finalY + 15;

  // FINAL OUTCOME
  if (currentY > pageHeight - 60) {
    doc.addPage();
    currentY = margin;
  }
  
  doc.setFillColor(240, 253, 250); // Light teal bg
  doc.setDrawColor(20, 184, 166);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, currentY, pageWidth - margin * 2, 35, 3, 3, "FD");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 118, 110);
  doc.text("Final Solution", margin + 5, currentY + 8);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  const outcomeText = prototype?.description || "No final solution documented.";
  const splitOutcome = doc.splitTextToSize(outcomeText, pageWidth - margin * 2 - 10);
  doc.text(splitOutcome.slice(0, 4), margin + 5, currentY + 15); // Max 4 lines roughly
  
  currentY += 45;

  // OVERALL SIMULATION SCORE & ACHIEVEMENTS
  if (currentY > pageHeight - 70) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text(`Overall Simulation Score: ${scores.overallScore}%`, margin, currentY);
  
  currentY += 6;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);
  let performanceTitle = "Developing Design Thinker";
  if (scores.overallScore >= 91) performanceTitle = "Excellent Design Thinking Performance";
  else if (scores.overallScore >= 76) performanceTitle = "Good Design Thinking Performance";
  
  doc.setTextColor(71, 85, 105);
  doc.text(performanceTitle, margin, currentY);
  
  currentY += 15;

  // Skills Demonstrated
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Skills Demonstrated:", margin, currentY);
  currentY += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("✔ Empathy   ✔ User Research   ✔ Problem Solving   ✔ Critical Thinking   ✔ Creativity   ✔ Innovation   ✔ Design Thinking", margin, currentY);
  currentY += 15;

  // Achievements
  if (userProfile?.unlockedBadgeIds && userProfile.unlockedBadgeIds.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("Achievements Unlocked:", margin, currentY);
    currentY += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    const badgesString = userProfile.unlockedBadgeIds.map((b: string) => `🏆 ${b.split('-').map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}`).join("   ");
    const splitBadges = doc.splitTextToSize(badgesString, pageWidth - margin * 2);
    doc.text(splitBadges, margin, currentY);
    currentY += splitBadges.length * 6 + 9;
  }

  // Final Reflection
  if (currentY > pageHeight - 40) {
    doc.addPage();
    currentY = margin;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("Final Reflection", margin, currentY);
  currentY += 6;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const reflectionText = "This report summarizes your Design Thinking journey through DT Innovation Lab. You successfully explored a real-world challenge, understood user needs, defined the right problem, generated innovative ideas, and built a solution-oriented prototype.";
  const splitRef = doc.splitTextToSize(reflectionText, pageWidth - margin * 2);
  doc.text(splitRef, margin, currentY);

  // Add Footers to all pages
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  doc.save(`DT_Innovation_Lab_Report_${Date.now()}.pdf`);
};
